sudo: required
services:
  - docker

before_install:
  - docker build -t codymarcus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codymarcus/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-638609742310"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
